@startuml
skinparam roundcorner 20
skinparam style strictuml

actor       Actor
participant Mediator
database    Database
control Network

Actor -> Mediator : getLessons()
Mediator -> Database : getCache()
alt#Gold #LightGreen Cache is fresh
    Database --> Mediator: Cache<List<Lesson>>
    Mediator --> Actor: Cache<List<Lesson>>
else #LightYellow Cache is absent or absolete
    Database --> Mediator : Cache<List<Lesson>>?
    Mediator -> Network : fetch()
    Network --> Mediator : List<Lesson>
    Mediator -> Database : save(List<Lesson>)
    Mediator --> Actor: List<Lesson>
end
@enduml